name: Bug Report
description: |
  Report a bug encountered while using Taichi. We've collected some common issue solutions in https://docs.taichi.graphics/lang/articles/misc/install. Make sure you've check them out first. Hopefully they could address your problem.
labels: 
  - "potential bug"
body:
  - type: textarea
    id: problem
    attributes:
      label: Describe the bug?
      description: |
        A clear and concise description of what the bug is, ideally within 20 words.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How To Reproduce?
      description: |
        Please post a **minimal sample code** to reproduce the bug.
        The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.
      value: |
        ```py
        # sample code here
        ```
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log/Screenshots?
      description: |
        Please post a **minimal sample code** to reproduce the bug.
        The developer team will put a higher priority on bugs that can be reproduced within 20 lines of code. If you want a prompt reply, please keep the sample code **short** and **representative**.
      value: |
        ```py
        # sample code here
        ```
      render: markdown
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log/Screenshots?
      description: |
        Please post the **full log** of the program (instead of just a few lines around the error message, unless the log is > 1000 lines). This will help us diagnose what's happening.
      value: |
        ```text
        $ python my_sample_code.py
        [Taichi] mode=release
        [Taichi] version 0.6.29, llvm 10.0.0, commit b63f6663, linux, python 3.8.3
        ```
      render: markdown
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional comments?
      description: |
        If possible, please also consider attaching the output of command `ti diagnose`. This produces the detailed environment information and hopefully helps us diagnose faster.